- name: install the catalogue iteam
  hosts: catalogue
  become: yes
  tasks: 

  - name: setup NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: install nodejs
    ansible.builtin.yum: 
      name: nodejs
      state: installed

  - name: check weather the roboshot user exist or not
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - when: out.rc!= 0
    name: create a roboshop user
    become: yes
    ansible.builtin.user: 
      name: roboshop

  - name: check weather the /app directory exists or not 
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the directory stats
    ansible.builtin.debug: 
      msg: "output: {{directory}}"

  - when: directory.stat.exists == false
    name: create /app directory
    ansible.builtin.file: 
      path: /app
      state: directory

  - name: downloadind the catalogue file
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: unzipping the ccatalogue files
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
      
      





    