- name: Install mongodb componenet
  hosts: mongodb
  become: yes
  tasks: 

  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy: 
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.yum: 
      name: mongodb-org
      state: installed

  - name: start and enable the mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes 