- name: install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks: 

  - name: config rabbitmq repos
    ansible.builtin.shell: "{{item}}"
    loop: 
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: install rabbitmq
    ansible.builtin.yum: 
      name: rabbitmq-server
      state: installed 

  - name: starting and enabling rabitmq
    ansible.builtin.service:
      name: rabbitmq
      state: restarted
      enabled: true 

  - name: create the user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: setup permissions
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
