- name: configure the web iteam
  hosts: web
  become: yes
  tasks: 

  - name: install nginx
    ansible.builtin.yum: 
      name: nginx
      state: installed

  - name: start and enable the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
      
  - name: Delete default html content 
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/

  - name: downloadind the web file
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: unzipping the web files
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy the roboshop conf
    ansible.builtin.copy: 
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf 


  - name: Restart service nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      


  